---
- name: win_file module demo
  hosts: all
  vars:
    mydir: 'C:\ansiblex'
  tasks:
  - name: Download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z2301-x64.exe
      dest: 'C:\ansiblex'
